---
- hosts: all
  become: true
  tasks:
   - name: Install HTTP in redhat server
     yum:
      name: httpd
      state: present
     when: ansible_os_family == "RedHat"
   - name: Install HTTP in ubuntu server
     apt:
      name: apache2
      state: present
     when: ansible_os_family == "Ubuntu"
...