- hosts: all
  become: true
  tasks:
   - name: create users
     user:
      name: "{{item.name}}"
      create_home: "{{item.createhome}}"
     loop:
       - { name: 'manvith', 'createhome': yes }
       - { name: 'amma', 'createhome': no }
       - { name: 'shruthi', 'createhome': yes }
...
